config/routes.rb
Rails.application.routes.draw do

root to: "sites#index"
get "/", to: "sites#index"
     

get   "/sessions/new", to: "sessions#new", as: "new_session"
post  "/sessions"    , to:  "sessions#create", as: "sessions"
delete  "/sessions"  , to:  "sessions#destroy", as: "session"

 resources :users
 resources :rides do
    resources :rideprices
  end

end

app/models/ride.rb
class Ride < ActiveRecord::Base
	belongs_to :user
	has_many :rideprices


end

app/models/rideprice.rb
class Rideprice < ActiveRecord::Base
	include HTTParty
	belongs_to :ride




end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :rides

	has_secure_password

	validates :email, :password, presence: true
	validates :email, uniqueness: true
	validates_confirmation_of :password
	# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100X100>"}, default_url: ":style/missing.png"
	# validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def self.confirm(params)
	user = User.find_by_email(params[:email])	
	user.try(:authenticate, params[:password])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :current_user

	include SessionsHelper
	include HTTParty
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rideprices_controller.rb
class RidepricesController < ApplicationController
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
before_action :right_user

  def index
    @current_user = current_user
    #why find_by does not capture all
    # @rides = Ride.find_by(:user_id => current_user.id)
    @rides = Ride.all.where(:user_id => current_user.id)
  end
  
  def new
  	@user = current_user
    @token = ENV["UBER_SERVICE_TOKEN"]
  	@ride = Ride.new
  end

  def show
  	@ride = Ride.find(params[:id])
  	@origin = @ride[:origin]
  	@destination = @ride[:destination]
    @ride_name = @ride[:ride_name]
    @uber = ENV['UBER_SERVICE_TOKEN']
  end


  def create
    @user = current_user
    ride_params = params.require(:ride).permit(:origin, :destination, :created_at, :updated_at, :origin_latitude, :origin_longitude ,:destination_latitude ,:destination_longitude ,:ride_name)
  	@ride = Ride.new(ride_params)
    @ride.user = current_user
  	if @ride.save 
  		redirect_to ride_path(@ride.id)
  	else
  	redirect_to new_ride_path
  	end
  end

  def edit
    ride_id = params[:id]
    @ride = Ride.find(ride_id) 

  end


  def update
    ride_id = params[:id]
    @ride = Ride.find(ride_id)
    params_updated = params.require(:ride).permit(:origin, :destination, :created_at, :updated_at, :origin_latitude, :origin_longitude ,:destination_latitude ,:destination_longitude ,:ride_name)
    @ride.update(params_updated)
    redirect_to ride_path

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user= User.new
  	render :new
  end

  def create
  	@user = User.confirm(user_params)
  	if @user
  		login(@user)
  		redirect_to user_path(@user.id)
  	else
  		redirect_to new_session_path
  	end
  end

  def destroy
  session[:user_id] = nil
 	redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
   before_action :current_user

   def index
	 	@user = User.new
	 	@disable_nav = true
	 	render :index
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in?, only: [:show, :index]
  
  def index
  	@user = User.new
  	render :index
  end
  
  def new
  	@user = User.new
  	render :new
  end

  def create
  	  @user = User.new(user_params)
    if @user.save
       login(@user)
       redirect_to user_path(@user.id)
    else
      render :new
    end
  end
	 
	 def show
	 	@user = User.find(params[:id])
	 	@current_user = current_user
    @disable_nav = true
 	 end

 	 def edit
    @user = User.find(params[:id])
    render :edit
     end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :age, :gender, :avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
 
 def controller?(*controller)
    controller.include?(params[:controller])
  end 

  def action?(*action)
    @current_action = action.include?(params[:action])
  end

  def current_page
  	current_page?(params[:action]) 
  end

end

app/helpers/rideprices_helper.rb
module RidepricesHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end


	def current_user
		@current_user ||= session[:user_id] && User.find(session[:user_id])
    end


    def right_user
        if !current_user 
            redirect_to new_session_path
        end
    end


    def logged_in?
    	if current_user == nil
    		redirect_to root_path
        end
    end
    

    def logout
    	@current_user = session[:user_id] = nil
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ridetrack</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
  <script type ="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<!-- verification for google -->
  <meta name="google-site-verification" content="T_PQhdeThJqwGk9ckWo-CpKIMMdbDw0wXGyjlR0lEZo" />
  
 <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

 <script src="https://code.jquery.com/jquery-1.10.2.js"></script> 

	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>

 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

<%= render "partials/nav"  unless @disable_nav %>
<%= yield %>

</body>
</html>

app/views/partials/_begmodal.html.erb
<div class="modal-dialog flip-wrapper">
  <div class="modal-content flip active" id="loginFlip">
    <div class="modal-body">
      <header class="header">

app/views/partials/_modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="false">
  <div class="modal-dialog flip-wrapper">
    <div class="modal-content flip active" id="loginFlip">
      <div class="modal-body">
        <header class="header">
          <p class="title">Log in</p>
        </header>
        <div class="alert alert-danger hide" id="errorWrapperLogin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div>
        <div class="form-controls">
          <div class="form-controls">
            <a id="auth-loginlink" href="#" class="btn-secondary btn-block btn-big" data-track-event="SignUpModal,SignUpWithFacebook"><i class="icon-facebook"></i>&nbsp;&nbsp;Log in with Facebook</a>
          </div>
          <div class="line-form-separator"></div>
          <div class="form-group">
            <%= form_for @user, url: "/sessions", method: "post" do |f| %>
            <%= f.text_field :email, placeholder: "Email", :class => "form-control" %><br>
            <%= f.password_field :password, placeholder: "Password", :class => "form-control" %>
          </div>
          <div class="form-controls">
            <%= f.submit "Sign In", :class => "btn-primary btn-block" %>
          </div>
            <% end %> 
         </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="false">
  <div class="modal-dialog flip-wrapper">
    <div class="modal-content flip active" id="loginFlip">
      <div class="modal-body">
        <header class="header">
          <p class="title">Sign up</p>
        </header>
        <div class="alert alert-danger hide" id="errorWrapperLogin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div>
        <div class="form-controls">
          <div class="form-controls">
            <a id="auth-loginlink" href="#" class="btn-secondary btn-block btn-big" data-track-event="SignUpModal,SignUpWithFacebook"><i class="icon-facebook"></i>&nbsp;&nbsp;Sign up with Facebook</a>
          </div>
          <div class="line-form-separator"></div>
          <div class="form-group">
          <%= form_for @user, :html => { :multipart => true } do |f| %>
            <% if @user.errors.any? %> 
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited sign up:</h2>
                <ul><% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              </div>
              <% end %>
            <% end %>
              <%= f.text_field :first_name, placeholder: "First Name", :class => "form-control" %><br>
              <%= f.text_field :last_name, placeholder: "Last Name", :class => "form-control" %><br>
              <%= f.text_field :email, placeholder: "Email", :class => "form-control" %><br>
              <%= f.password_field :password, placeholder: "Password", :class => "form-control" %><br>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", :class => "form-control" %><br>
            <div class="form-group">
              <%= f.submit "Sign In", :class => "btn-primary btn-block" %>
            </div>
              <%end%>
         </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
  instagram();
  </script>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Ridetrack", root_path, :"data-no-turbolink" => true, :class => "navbar-brand"%>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

      <% if @current_user %>
          <%if controller?("rides") && action?("show")%> 
              <%= link_to "Save Ride", ride_path, :class => "btn btn-success", method: :patch%>
             <a><%= link_to 'Edit Ride', edit_ride_path, :class => "btn btn-success"%></a>
          <%end%>

        <li><%=link_to "Profile", user_path(current_user), method: :get%></li>
				<li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.first_name.capitalize %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user), method: :get%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", session_path, method: :delete%></a></li>
           <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  </div>
</nav>

app/views/rides/create.html.erb
<h1>Rides#create</h1>
<p>Find me in app/views/rides/create.html.erb</p>

app/views/rides/edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <header class="header">
          <p class="title">Edit Ride</p>
        </header>

		<%= form_for @ride, url: ride_path, method: "patch" do |f|%>
			<%= f.text_field :origin, :placeholder => @origin, :class => "form-control", :id => "autocomplete"%><br></div>
			<%= f.text_field  :destination, :placeholder => @destination, :class => "form-control", :id => "autocompleteEnd"%><br>
			<%= f.text_field :ride_name, :placeholder => "Ride Name", :class => "form-control", :id => "ride-name"%><br>
			<%= f.hidden_field :origin_latitude, :class => "form-control", :id => "oLatitude"%><br>
			<%= f.hidden_field :origin_longitude, :class => "form-control", :id => "olongitude"%><br>
			<%= f.submit "Save Changes", :class => "btn-primary btn-block", :id => "callRide" %><br>
       <%end%>

    </div>
   </div>
  </div>
  
 <script type="text/javascript">
  
  initAutocomplete();

  </script>

app/views/rides/index.html.erb
<h1>Rides Index Page</h1>


<% @rides.each do |r, index| %>

<h1><%= link_to r.ride_name, ride_path(r[:id]) %> </h1>
<ul><%= r[:origin]%></ul>
<ul><%= r[:destination]%></ul>
<% end%>

app/views/rides/new.html.erb
 <%= render "partials/begmodal" %>


<div class="form-controls">
	<div class="new-ride">
	<h1>Track a New Ride</h1>
    </div>
	<div class="line-form-separator"></div>
	<div class="form-group">
<%= form_for @ride, url: rides_path, method: "post" do |f|%>
<%= f.text_field :origin, :placeholder => "Origin Address", :class => "form-control", :id => "autocomplete"%><br>
<%= f.text_field :destination, :placeholder => "Destination Address", :class => "form-control", :id => "autocompleteEnd"%><br>
<%= f.text_field :ride_name, :placeholder => "Ride Name", :class => "form-control"%><br>
<%= f.hidden_field :origin_latitude, :class => "form-control", :id => "oLatitude"%><br>
<%= f.hidden_field :origin_longitude, :class => "form-control", :id => "olongitude"%><br>
<%= f.submit "Ridetrack Now", :class => "btn-primary btn-block", :id => "callRide" %><br>
<%end%>
</div>
</div>

<script type="text/javascript">
initAutocomplete();
</script>

app/views/rides/show.html.erb
<div id ="map"></div>
<h1>Start Tracking Now</h1>
<div class="ride-info">
<h4>
<div id = "uber" data-string="<%=@uber%>"></div>	
<div id = "oAddress" data-string="<%=@origin%>">Origin Address: <%= @origin%></div>
<div id="dAddress" data-string="<%=@destination%>">Destination Address: <%= @destination%></div></br>
<div id="ride-cost"></div>
<div id="myRide" data-string="<%@ride.ride_name%>">Ride Name: <%= @ride.ride_name%></div>
</h4>
</div>

<div class="container">
  <h2>Uber Ride Prices At Current Time</h2>
  <div>
    <canvas id="canvas"></canvas>
  </div>
</div>
<div id="warnings-panel"></div>

 <script type="text/javascript">
ridetrack();

</script>

app/views/sites/index.html.erb
<div id="sites-index-page-wrapper">   
 <section id="hero-section">
  <div id="bgndVideo" class="player" 
      data-property= "{videoURL:'http://youtu.be/uw08j-yOfcE',containment:self,autoPlay: true, mute:true, startAt: 5, opacity: 1, addRast
      er: true, stopAt: 75.5, showControls:false, stopMovieOnBlur:false}">
    </div>

 <div class="navbarsplash">

    	<div class="navbarsplash-inner">
    		<div class="navbarsplash-login">
             <%if current_user %>
              <a><%= link_to "Profile", user_path(session[:user_id]), method: :get, :class => "btn-signup"%></a> 
              <a><%=link_to "Log out", session_path, method: :delete, :class => "btn-login"%></a>
            <% else %>
    				<a href="#signupModal" data-toggle="modal" data-toggle-flip data-toggle-flip-target="#registerFlip" data-track-event="SignUpModal,TopbarBtn" class="btn-signup" id="registerBtn">Sign up</a>
    				<a href="#loginModal" data-toggle="modal" data-toggle-flip data-toggle-flip-target="#loginFlip" data-directive="login" data-track-event="LogInModal,TopbarBtn" class="btn-login" id="loginBtn"><i class="icon-user"></i> Log in</a>
    			</div>
          <%end%>
    	</div>
    </div>
    <section id="home" class="video">
    	<div class="main-splash row">
    		<div class="inner">
          <!-- <a href="#signupModal" data-toggle="modal" data-toggle-flip data-toggle-flip-target="#registerFlip" data-<!-- track-event="SignUpModal,TopbarBtn" class="btn-primary" id="registerBtn">Ridetrack Now!</a> --> 
            <h1> Ridetrack </h1>
            <h2> Commute Cost Tracking Tool</h2>
    		</div>
    	</div>
    </section>
  </section>
  
<!-- Modal -->
  <%= render "partials/modal" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
  <!-- render "partials/begmodal" only needed for styling of this form -->
<!--   <%= render "partials/begmodal" %> -->

  <div class="modal-dialog flip-wrapper">
  <div class="modal-content flip active" id="loginFlip">
    <div class="modal-body">
      <header class="header">

          <p class="title">Sign up</p>
        </header>
        <div class="alert alert-danger hide" id="errorWrapperLogin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div>
        <div class="form-controls">
          <div class="form-controls">
            <a id="auth-loginlink" href="#" class="btn-secondary btn-block btn-big" data-track-event="SignUpModal,SignUpWithFacebook"><i class="icon-facebook"></i>&nbsp;&nbsp;Sign up with Facebook</a>
          </div>
          <div class="line-form-separator"></div>
          <div class="form-group">
          <%= form_for @user, :html => { :multipart => true } do |f| %>
            <% if @user.errors.any? %> 
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited sign up:</h2>
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              </div>
                <% end %>
              <% end %>
              <%= f.text_field :first_name, placeholder: "First Name", :class => "form-control" %><br>
              <%= f.text_field :last_name, placeholder: "Last Name", :class => "form-control" %><br>
              <%= f.text_field :email, placeholder: "Email", :class => "form-control" %><br>
              <%= f.password_field :password, placeholder: "Password", :class => "form-control" %><br>
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", :class => "form-control" %><br>
            <div class="form-group">
              <%= f.submit "Sign In", :class => "btn-primary btn-block" %>
            </div>
            <%end%>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Ridetrack", root_path, :"data-no-turbolink" => true, :class => "navbar-brand"%>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
        <li><%=link_to "New Ride", new_ride_path, method: :get%></li>
        <li><%=link_to "My Rides", rides_path , method: :get%> </li>
        
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, <%= @current_user.first_name.capitalize %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path(current_user), method: :get%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", session_path, method: :delete%></a></li>

            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  </div>
</nav>